CREATE DATABASE IF NOT EXISTS GA;
CREATE TABLE IF NOT EXISTS GA.GA (id INT(10) PRIMARY KEY auto_increment, pid int(10), clus VARCHAR(100) NOT NULL, model LONGTEXT NOT NULL, score FLOAT NOT NULL, tscore FLOAT NOT NULL);
CREATE TABLE IF NOT EXISTS GA.SOLS (id INT(10) PRIMARY KEY auto_increment, pid int(10), fold INT(5) NOT NULL, sol VARCHAR(100) NOT NULL, score FLOAT NOT NULL, tscore FLOAT NOT NULL);
CREATE TABLE IF NOT EXISTS GA.NODES (id INT(10) PRIMARY KEY auto_increment, pid int(10), node INT(10) NOT NULL, score FLOAT NOT NULL, visits INT(10) NOT NULL);
CREATE TABLE IF NOT EXISTS GA.GENES (id INT(10) PRIMARY KEY auto_increment, pid int(10), name VARCHAR(50) NOT NULL, go VARCHAR(50), des longtext);
CREATE TABLE IF NOT EXISTS GA.FOLDS (id INT(10) PRIMARY KEY auto_increment, pid int(10), fold INT(5) NOT NULL, gene INT(5));
